# Generated by Django 2.2.11 on 2020-03-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcode', models.CharField(db_index=True, default='BLAHBLAH', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('GuidetoPharma', models.CharField(max_length=200)),
                ('DrugCentral', models.CharField(max_length=200)),
                ('BindingDB', models.CharField(max_length=200)),
                ('ChEMBL', models.CharField(max_length=200)),
                ('Orphanet', models.CharField(max_length=200)),
                ('DisGeNET', models.CharField(max_length=200)),
                ('PDB', models.CharField(max_length=200)),
                ('PDBnum', models.IntegerField()),
            ],
            options={
                'ordering': ['idcode'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugid', models.CharField(default='BLAHBLAH2', max_length=200)),
                ('drugname', models.CharField(max_length=200)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.Molecule')),
            ],
            options={
                'ordering': ['drugid'],
            },
        ),
    ]
