# Generated by Django 2.2.11 on 2020-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='BindingDB',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='ChEMBL',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='DisGeNET',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='Orphanet',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='PDB',
            field=models.CharField(max_length=1000),
        ),
    ]
