# Generated by Django 2.2.11 on 2020-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20200319_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drugid',
            field=models.CharField(db_index=True, default='BLAHBLAH2', max_length=200),
        ),
    ]
